#############################################################################
# Makefile for building: QChurchView
# Generated by qmake (2.01a) (Qt 4.5.1) on: qui set 3 15:57:12 2009
# Project:  QChurchView.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile QChurchView.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_PHONON_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=i686 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=i686 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/phonon -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/qt4 -lphonon -lQtGui -L/usr/lib/qt4 -L/usr/X11R6/lib -pthread -lpng -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lXrandr -lXinerama -lfontconfig -lXext -lX11 -lQtCore -lz -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = qfrmconfigslidepadrao.cpp \
		qoutputwindow.cpp \
		zutil.c \
		QfileQts.cpp \
		QfileQvs.cpp \
		tinystr.cpp \
		tinyxml.cpp \
		tinyxmlerror.cpp \
		tinyxmlparser.cpp \
		CConfig.cpp \
		qfrmconfigdirs.cpp \
		qtabmain.cpp \
		main.cpp \
		qchurchview.cpp moc_qfrmconfigslidepadrao.cpp \
		moc_qoutputwindow.cpp \
		moc_qfrmconfigdirs.cpp \
		moc_qtabmain.cpp \
		moc_qchurchview.cpp \
		qrc_Img.cpp
OBJECTS       = qfrmconfigslidepadrao.o \
		qoutputwindow.o \
		zutil.o \
		QfileQts.o \
		QfileQvs.o \
		tinystr.o \
		tinyxml.o \
		tinyxmlerror.o \
		tinyxmlparser.o \
		CConfig.o \
		qfrmconfigdirs.o \
		qtabmain.o \
		main.o \
		qchurchview.o \
		moc_qfrmconfigslidepadrao.o \
		moc_qoutputwindow.o \
		moc_qfrmconfigdirs.o \
		moc_qtabmain.o \
		moc_qchurchview.o \
		qrc_Img.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		QChurchView.pro
QMAKE_TARGET  = QChurchView
DESTDIR       = 
TARGET        = QChurchView

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_qfrmconfigslidepadrao.h ui_qfrmconfigdirs.h ui_qtabmain.h ui_qchurchview.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QChurchView.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/qt4/libQtGui.prl \
		/usr/lib/qt4/libQtCore.prl
	$(QMAKE) -unix -o Makefile QChurchView.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/qt4/libQtGui.prl:
/usr/lib/qt4/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile QChurchView.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QChurchView1.0.0 || $(MKDIR) .tmp/QChurchView1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QChurchView1.0.0/ && $(COPY_FILE) --parents qfrmconfigslidepadrao.h qoutputwindow.h zconf.h zlib.h zutil.h QfileQts.h QfileQts.h QfileQts.h QfileQvs.h CConfig.h qfrmconfigdirs.h qtabmain.h qchurchview.h .tmp/QChurchView1.0.0/ && $(COPY_FILE) --parents Img.qrc .tmp/QChurchView1.0.0/ && $(COPY_FILE) --parents qfrmconfigslidepadrao.cpp qoutputwindow.cpp zutil.c QfileQts.cpp QfileQvs.cpp tinystr.cpp tinyxml.cpp tinyxmlerror.cpp tinyxmlparser.cpp CConfig.cpp qfrmconfigdirs.cpp qtabmain.cpp main.cpp qchurchview.cpp .tmp/QChurchView1.0.0/ && $(COPY_FILE) --parents qfrmconfigslidepadrao.ui qfrmconfigdirs.ui qtabmain.ui qchurchview.ui .tmp/QChurchView1.0.0/ && (cd `dirname .tmp/QChurchView1.0.0` && $(TAR) QChurchView1.0.0.tar QChurchView1.0.0 && $(COMPRESS) QChurchView1.0.0.tar) && $(MOVE) `dirname .tmp/QChurchView1.0.0`/QChurchView1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QChurchView1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qfrmconfigslidepadrao.cpp moc_qoutputwindow.cpp moc_qfrmconfigdirs.cpp moc_qtabmain.cpp moc_qchurchview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qfrmconfigslidepadrao.cpp moc_qoutputwindow.cpp moc_qfrmconfigdirs.cpp moc_qtabmain.cpp moc_qchurchview.cpp
moc_qfrmconfigslidepadrao.cpp: ui_qfrmconfigslidepadrao.h \
		qfrmconfigslidepadrao.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qfrmconfigslidepadrao.h -o moc_qfrmconfigslidepadrao.cpp

moc_qoutputwindow.cpp: consts.h \
		qoutputwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qoutputwindow.h -o moc_qoutputwindow.cpp

moc_qfrmconfigdirs.cpp: ui_qfrmconfigdirs.h \
		qfrmconfigdirs.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qfrmconfigdirs.h -o moc_qfrmconfigdirs.cpp

moc_qtabmain.cpp: QfileQts.h \
		tinyxml.h \
		tinystr.h \
		zlib.h \
		zconf.h \
		QfileQvs.h \
		qoutputwindow.h \
		consts.h \
		ui_qtabmain.h \
		qtabmain.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qtabmain.h -o moc_qtabmain.cpp

moc_qchurchview.cpp: ui_qchurchview.h \
		CConfig.h \
		tinyxml.h \
		tinystr.h \
		qtabmain.h \
		QfileQts.h \
		zlib.h \
		zconf.h \
		QfileQvs.h \
		qoutputwindow.h \
		consts.h \
		ui_qtabmain.h \
		qfrmconfigdirs.h \
		ui_qfrmconfigdirs.h \
		qfrmconfigslidepadrao.h \
		ui_qfrmconfigslidepadrao.h \
		qchurchview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qchurchview.h -o moc_qchurchview.cpp

compiler_rcc_make_all: qrc_Img.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Img.cpp
qrc_Img.cpp: Img.qrc \
		img/vis_tema.jpg
	/usr/bin/rcc -name Img Img.qrc -o qrc_Img.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_qfrmconfigslidepadrao.h ui_qfrmconfigdirs.h ui_qtabmain.h ui_qchurchview.h
compiler_uic_clean:
	-$(DEL_FILE) ui_qfrmconfigslidepadrao.h ui_qfrmconfigdirs.h ui_qtabmain.h ui_qchurchview.h
ui_qfrmconfigslidepadrao.h: qfrmconfigslidepadrao.ui
	/usr/bin/uic qfrmconfigslidepadrao.ui -o ui_qfrmconfigslidepadrao.h

ui_qfrmconfigdirs.h: qfrmconfigdirs.ui
	/usr/bin/uic qfrmconfigdirs.ui -o ui_qfrmconfigdirs.h

ui_qtabmain.h: qtabmain.ui
	/usr/bin/uic qtabmain.ui -o ui_qtabmain.h

ui_qchurchview.h: qchurchview.ui
	/usr/bin/uic qchurchview.ui -o ui_qchurchview.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

qfrmconfigslidepadrao.o: qfrmconfigslidepadrao.cpp qfrmconfigslidepadrao.h \
		ui_qfrmconfigslidepadrao.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qfrmconfigslidepadrao.o qfrmconfigslidepadrao.cpp

qoutputwindow.o: qoutputwindow.cpp qoutputwindow.h \
		consts.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qoutputwindow.o qoutputwindow.cpp

zutil.o: zutil.c zutil.h \
		zlib.h \
		zconf.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o zutil.o zutil.c

QfileQts.o: QfileQts.cpp QfileQts.h \
		tinyxml.h \
		tinystr.h \
		zlib.h \
		zconf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QfileQts.o QfileQts.cpp

QfileQvs.o: QfileQvs.cpp QfileQvs.h \
		tinyxml.h \
		tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QfileQvs.o QfileQvs.cpp

tinystr.o: tinystr.cpp tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinystr.o tinystr.cpp

tinyxml.o: tinyxml.cpp tinyxml.h \
		tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinyxml.o tinyxml.cpp

tinyxmlerror.o: tinyxmlerror.cpp tinyxml.h \
		tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinyxmlerror.o tinyxmlerror.cpp

tinyxmlparser.o: tinyxmlparser.cpp tinyxml.h \
		tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinyxmlparser.o tinyxmlparser.cpp

CConfig.o: CConfig.cpp CConfig.h \
		tinyxml.h \
		tinystr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CConfig.o CConfig.cpp

qfrmconfigdirs.o: qfrmconfigdirs.cpp qfrmconfigdirs.h \
		ui_qfrmconfigdirs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qfrmconfigdirs.o qfrmconfigdirs.cpp

qtabmain.o: qtabmain.cpp qtabmain.h \
		QfileQts.h \
		tinyxml.h \
		tinystr.h \
		zlib.h \
		zconf.h \
		QfileQvs.h \
		qoutputwindow.h \
		consts.h \
		ui_qtabmain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtabmain.o qtabmain.cpp

main.o: main.cpp qchurchview.h \
		ui_qchurchview.h \
		CConfig.h \
		tinyxml.h \
		tinystr.h \
		qtabmain.h \
		QfileQts.h \
		zlib.h \
		zconf.h \
		QfileQvs.h \
		qoutputwindow.h \
		consts.h \
		ui_qtabmain.h \
		qfrmconfigdirs.h \
		ui_qfrmconfigdirs.h \
		qfrmconfigslidepadrao.h \
		ui_qfrmconfigslidepadrao.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qchurchview.o: qchurchview.cpp qchurchview.h \
		ui_qchurchview.h \
		CConfig.h \
		tinyxml.h \
		tinystr.h \
		qtabmain.h \
		QfileQts.h \
		zlib.h \
		zconf.h \
		QfileQvs.h \
		qoutputwindow.h \
		consts.h \
		ui_qtabmain.h \
		qfrmconfigdirs.h \
		ui_qfrmconfigdirs.h \
		qfrmconfigslidepadrao.h \
		ui_qfrmconfigslidepadrao.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qchurchview.o qchurchview.cpp

moc_qfrmconfigslidepadrao.o: moc_qfrmconfigslidepadrao.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qfrmconfigslidepadrao.o moc_qfrmconfigslidepadrao.cpp

moc_qoutputwindow.o: moc_qoutputwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qoutputwindow.o moc_qoutputwindow.cpp

moc_qfrmconfigdirs.o: moc_qfrmconfigdirs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qfrmconfigdirs.o moc_qfrmconfigdirs.cpp

moc_qtabmain.o: moc_qtabmain.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtabmain.o moc_qtabmain.cpp

moc_qchurchview.o: moc_qchurchview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qchurchview.o moc_qchurchview.cpp

qrc_Img.o: qrc_Img.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Img.o qrc_Img.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

